apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vault
spec:
  hosts:
  - "*"
  gateways:
  - vault
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: helm-vault
        port:
          number: 80                   