apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vault
spec:
  hosts:
  - "*"
  gateways:
  - vault
  http:
  - match:
    - uri:
        exact: /vault
    route:
    - destination:
        host: helm-vault.vault.svc.cluster.local
        port:
          number: 8200                   